### ISSUE TITLE
I can not open Events en mi dashboard 

### ISSUE THREAD

**Issue by zarlo12** [OCA/event#173]
Hello, i need your help, after install the module in odoo 12, i can not open *EVENTS* in my dashboard :(

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/dietline/odoo/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/dietline/odoo/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/dietline/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/dietline/odoo/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/dietline/odoo/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/dietline/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/dietline/odoo/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/dietline/odoo/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/dietline/odoo/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/dietline/odoo/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/dietline/odoo/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/dietline/odoo/odoo/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/home/dietline/odoo/odoo/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/dietline/odoo/odoo/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/home/dietline/odoo/odoo/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/home/dietline/odoo/odoo/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/home/dietline/odoo/odoo/odoo/models.py", line 1462, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/home/dietline/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 1106, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/home/dietline/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: El campo `priority` no existe

Contexto del error:
Vista `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]
```

**Comment by pedrobaeza** [comment]
Which module of this repo have you installed?
